// ignore_for_file: constant_identifier_names
class ResponseCode {
  final int code;
  final String name;

  const ResponseCode._(this.code, this.name);

  static const int OK = 0;
  static const int INVALID_TRANSACTION = 1;
  static const int PAYER_ACCOUNT_NOT_FOUND = 2;
  static const int INVALID_NODE_ACCOUNT = 3;
  static const int TRANSACTION_EXPIRED = 4;
  static const int INVALID_TRANSACTION_START = 5;
  static const int INVALID_TRANSACTION_DURATION = 6;
  static const int INVALID_SIGNATURE = 7;
  static const int MEMO_TOO_LONG = 8;
  static const int INSUFFICIENT_TX_FEE = 9;
  static const int INSUFFICIENT_PAYER_BALANCE = 10;
  static const int DUPLICATE_TRANSACTION = 11;
  static const int BUSY = 12;
  static const int NOT_SUPPORTED = 13;
  static const int INVALID_FILE_ID = 14;
  static const int INVALID_ACCOUNT_ID = 15;
  static const int INVALID_CONTRACT_ID = 16;
  static const int INVALID_TRANSACTION_ID = 17;
  static const int RECEIPT_NOT_FOUND = 18;
  static const int RECORD_NOT_FOUND = 19;
  static const int INVALID_SOLIDITY_ID = 20;
  static const int UNKNOWN = 21;
  static const int SUCCESS = 22;
  static const int FAIL_INVALID = 23;
  static const int FAIL_FEE = 24;
  static const int FAIL_BALANCE = 25;
  static const int KEY_REQUIRED = 26;
  static const int BAD_ENCODING = 27;
  static const int INSUFFICIENT_ACCOUNT_BALANCE = 28;
  static const int INVALID_SOLIDITY_ADDRESS = 29;
  static const int INSUFFICIENT_GAS = 30;
  static const int CONTRACT_SIZE_LIMIT_EXCEEDED = 31;
  static const int LOCAL_CALL_MODIFICATION_EXCEPTION = 32;
  static const int CONTRACT_REVERT_EXECUTED = 33;
  static const int CONTRACT_EXECUTION_EXCEPTION = 34;
  static const int INVALID_RECEIVING_NODE_ACCOUNT = 35;
  static const int MISSING_QUERY_HEADER = 36;
  static const int ACCOUNT_UPDATE_FAILED = 37;
  static const int INVALID_KEY_ENCODING = 38;
  static const int NULL_SOLIDITY_ADDRESS = 39;
  static const int CONTRACT_UPDATE_FAILED = 40;
  static const int INVALID_QUERY_HEADER = 41;
  static const int INVALID_FEE_SUBMITTED = 42;
  static const int INVALID_PAYER_SIGNATURE = 43;
  static const int KEY_NOT_PROVIDED = 44;
  static const int INVALID_EXPIRATION_TIME = 45;
  static const int NO_WACL_KEY = 46;
  static const int FILE_CONTENT_EMPTY = 47;
  static const int INVALID_ACCOUNT_AMOUNTS = 48;
  static const int EMPTY_TRANSACTION_BODY = 49;
  static const int INVALID_TRANSACTION_BODY = 50;
  static const int INVALID_SIGNATURE_TYPE_MISMATCHING_KEY = 51;
  static const int INVALID_SIGNATURE_COUNT_MISMATCHING_KEY = 52;
  static const int EMPTY_LIVE_HASH_BODY = 53;
  static const int EMPTY_LIVE_HASH = 54;
  static const int EMPTY_LIVE_HASH_KEYS = 55;
  static const int INVALID_LIVE_HASH_SIZE = 56;
  static const int EMPTY_QUERY_BODY = 57;
  static const int EMPTY_LIVE_HASH_QUERY = 58;
  static const int LIVE_HASH_NOT_FOUND = 59;
  static const int ACCOUNT_ID_DOES_NOT_EXIST = 60;
  static const int LIVE_HASH_ALREADY_EXISTS = 61;
  static const int INVALID_FILE_WACL = 62;
  static const int SERIALIZATION_FAILED = 63;
  static const int TRANSACTION_OVERSIZE = 64;
  static const int TRANSACTION_TOO_MANY_LAYERS = 65;
  static const int CONTRACT_DELETED = 66;
  static const int PLATFORM_NOT_ACTIVE = 67;
  static const int KEY_PREFIX_MISMATCH = 68;
  static const int PLATFORM_TRANSACTION_NOT_CREATED = 69;
  static const int INVALID_RENEWAL_PERIOD = 70;
  static const int INVALID_PAYER_ACCOUNT_ID = 71;
  static const int ACCOUNT_DELETED = 72;
  static const int FILE_DELETED = 73;
  static const int ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS = 74;
  static const int SETTING_NEGATIVE_ACCOUNT_BALANCE = 75;
  static const int OBTAINER_REQUIRED = 76;
  static const int OBTAINER_SAME_CONTRACT_ID = 77;
  static const int OBTAINER_DOES_NOT_EXIST = 78;
  static const int MODIFYING_IMMUTABLE_CONTRACT = 79;
  static const int FILE_SYSTEM_EXCEPTION = 80;
  static const int AUTORENEW_DURATION_NOT_IN_RANGE = 81;
  static const int ERROR_DECODING_BYTESTRING = 82;
  static const int CONTRACT_FILE_EMPTY = 83;
  static const int CONTRACT_BYTECODE_EMPTY = 84;
  static const int INVALID_INITIAL_BALANCE = 85;
  static const int INVALID_RECEIVE_RECORD_THRESHOLD = 86; // [Deprecated]
  static const int INVALID_SEND_RECORD_THRESHOLD = 87; // [Deprecated]
  static const int ACCOUNT_IS_NOT_GENESIS_ACCOUNT = 88;
  static const int PAYER_ACCOUNT_UNAUTHORIZED = 89;
  static const int INVALID_FREEZE_TRANSACTION_BODY = 90;
  static const int FREEZE_TRANSACTION_BODY_NOT_FOUND = 91;
  static const int TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 92;
  static const int RESULT_SIZE_LIMIT_EXCEEDED = 93;
  static const int NOT_SPECIAL_ACCOUNT = 94;
  static const int CONTRACT_NEGATIVE_GAS = 95;
  static const int CONTRACT_NEGATIVE_VALUE = 96;
  static const int INVALID_FEE_FILE = 97;
  static const int INVALID_EXCHANGE_RATE_FILE = 98;
  static const int INSUFFICIENT_LOCAL_CALL_GAS = 99;
  static const int ENTITY_NOT_ALLOWED_TO_DELETE = 100;
  static const int AUTHORIZATION_FAILED = 101;
  static const int FILE_UPLOADED_PROTO_INVALID = 102;
  static const int FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK = 103;
  static const int FEE_SCHEDULE_FILE_PART_UPLOADED = 104;
  static const int EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED = 105;
  static const int MAX_CONTRACT_STORAGE_EXCEEDED = 106;
  static const int TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT = 107;
  static const int TOTAL_LEDGER_BALANCE_INVALID = 108;
  static const int EXPIRATION_REDUCTION_NOT_ALLOWED = 110;
  static const int MAX_GAS_LIMIT_EXCEEDED = 111;
  static const int MAX_FILE_SIZE_EXCEEDED = 112;
  static const int INVALID_TOPIC_ID = 150;
  static const int INVALID_ADMIN_KEY = 155;
  static const int INVALID_SUBMIT_KEY = 156;
  static const int UNAUTHORIZED = 157;
  static const int INVALID_TOPIC_MESSAGE = 158;
  static const int INVALID_AUTORENEW_ACCOUNT = 159;
  static const int AUTORENEW_ACCOUNT_NOT_ALLOWED = 160;
  static const int TOPIC_EXPIRED = 162;
  static const int INVALID_CHUNK_NUMBER = 163;
  static const int INVALID_CHUNK_TRANSACTION_ID = 164;
  static const int ACCOUNT_FROZEN_FOR_TOKEN = 165;
  static const int TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED = 166;
  static const int INVALID_TOKEN_ID = 167;
  static const int INVALID_TOKEN_DECIMALS = 168;
  static const int INVALID_TOKEN_INITIAL_SUPPLY = 169;
  static const int INVALID_TREASURY_ACCOUNT_FOR_TOKEN = 170;
  static const int INVALID_TOKEN_SYMBOL = 171;
  static const int TOKEN_HAS_NO_FREEZE_KEY = 172;
  static const int TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN = 173;
  static const int MISSING_TOKEN_SYMBOL = 174;
  static const int TOKEN_SYMBOL_TOO_LONG = 175;
  static const int ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN = 176;
  static const int TOKEN_HAS_NO_KYC_KEY = 177;
  static const int INSUFFICIENT_TOKEN_BALANCE = 178;
  static const int TOKEN_WAS_DELETED = 179;
  static const int TOKEN_HAS_NO_SUPPLY_KEY = 180;
  static const int TOKEN_HAS_NO_WIPE_KEY = 181;
  static const int INVALID_TOKEN_MINT_AMOUNT = 182;
  static const int INVALID_TOKEN_BURN_AMOUNT = 183;
  static const int TOKEN_NOT_ASSOCIATED_TO_ACCOUNT = 184;
  static const int CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT = 185;
  static const int INVALID_KYC_KEY = 186;
  static const int INVALID_WIPE_KEY = 187;
  static const int INVALID_FREEZE_KEY = 188;
  static const int INVALID_SUPPLY_KEY = 189;
  static const int MISSING_TOKEN_NAME = 190;
  static const int TOKEN_NAME_TOO_LONG = 191;
  static const int INVALID_WIPING_AMOUNT = 192;
  static const int TOKEN_IS_IMMUTABLE = 193;
  static const int TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT = 194;
  static const int TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES = 195;
  static const int ACCOUNT_IS_TREASURY = 196;
  static const int TOKEN_ID_REPEATED_IN_TOKEN_LIST = 197;
  static const int TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 198;
  static const int EMPTY_TOKEN_TRANSFER_BODY = 199;
  static const int EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS = 200;
  static const int INVALID_SCHEDULE_ID = 201;
  static const int SCHEDULE_IS_IMMUTABLE = 202;
  static const int INVALID_SCHEDULE_PAYER_ID = 203;
  static const int INVALID_SCHEDULE_ACCOUNT_ID = 204;
  static const int NO_NEW_VALID_SIGNATURES = 205;
  static const int UNRESOLVABLE_REQUIRED_SIGNERS = 206;
  static const int SCHEDULED_TRANSACTION_NOT_IN_WHITELIST = 207;
  static const int SOME_SIGNATURES_WERE_INVALID = 208;
  static const int TRANSACTION_ID_FIELD_NOT_ALLOWED = 209;
  static const int IDENTICAL_SCHEDULE_ALREADY_CREATED = 210;
  static const int INVALID_ZERO_BYTE_IN_STRING = 211;
  static const int SCHEDULE_ALREADY_DELETED = 212;
  static const int SCHEDULE_ALREADY_EXECUTED = 213;
  static const int MESSAGE_SIZE_TOO_LARGE = 214;
  static const int OPERATION_REPEATED_IN_BUCKET_GROUPS = 215;
  static const int BUCKET_CAPACITY_OVERFLOW = 216;
  static const int NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION = 217;
  static const int BUCKET_HAS_NO_THROTTLE_GROUPS = 218;
  static const int THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC = 219;
  static const int SUCCESS_BUT_MISSING_EXPECTED_OPERATION = 220;
  static const int UNPARSEABLE_THROTTLE_DEFINITIONS = 221;
  static const int INVALID_THROTTLE_DEFINITIONS = 222;
  static const int ACCOUNT_EXPIRED_AND_PENDING_REMOVAL = 223;
  static const int INVALID_TOKEN_MAX_SUPPLY = 224;
  static const int INVALID_TOKEN_NFT_SERIAL_NUMBER = 225;
  static const int INVALID_NFT_ID = 226;
  static const int METADATA_TOO_LONG = 227;
  static const int BATCH_SIZE_LIMIT_EXCEEDED = 228;
  static const int INVALID_QUERY_RANGE = 229;
  static const int FRACTION_DIVIDES_BY_ZERO = 230;
  static const int INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231;
  static const int CUSTOM_FEES_LIST_TOO_LONG = 232;
  static const int INVALID_CUSTOM_FEE_COLLECTOR = 233;
  static const int INVALID_TOKEN_ID_IN_CUSTOM_FEES = 234;
  static const int TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR = 235;
  static const int TOKEN_MAX_SUPPLY_REACHED = 236;
  static const int SENDER_DOES_NOT_OWN_NFT_SERIAL_NO = 237;
  static const int CUSTOM_FEE_NOT_FULLY_SPECIFIED = 238;
  static const int CUSTOM_FEE_MUST_BE_POSITIVE = 239;
  static const int TOKEN_HAS_NO_FEE_SCHEDULE_KEY = 240;
  static const int CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE = 241;
  static const int ROYALTY_FRACTION_CANNOT_EXCEED_ONE = 242;
  static const int FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT = 243;
  static const int CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES = 244;
  static const int CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON = 245;
  static const int CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 246;
  static const int INVALID_CUSTOM_FEE_SCHEDULE_KEY = 247;
  static const int INVALID_TOKEN_MINT_METADATA = 248;
  static const int INVALID_TOKEN_BURN_METADATA = 249;
  static const int CURRENT_TREASURY_STILL_OWNS_NFTS = 250;
  static const int ACCOUNT_STILL_OWNS_NFTS = 251;
  static const int TREASURY_MUST_OWN_BURNED_NFT = 252;
  static const int ACCOUNT_DOES_NOT_OWN_WIPED_NFT = 253;
  static const int ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON =
      254;
  static const int MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED = 255;
  static const int PAYER_ACCOUNT_DELETED = 256;
  static const int CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH = 257;
  static const int CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS = 258;
  static const int INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE = 259;
  static const int SERIAL_NUMBER_LIMIT_REACHED = 260;
  static const int CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE =
      261;
  static const int NO_REMAINING_AUTOMATIC_ASSOCIATIONS = 262;
  static const int EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT = 263;
  static const int
  REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT = 264;
  static const int TOKEN_IS_PAUSED = 265;
  static const int TOKEN_HAS_NO_PAUSE_KEY = 266;
  static const int INVALID_PAUSE_KEY = 267;
  static const int FREEZE_UPDATE_FILE_DOES_NOT_EXIST = 268;
  static const int FREEZE_UPDATE_FILE_HASH_DOES_NOT_MATCH = 269;
  static const int NO_UPGRADE_HAS_BEEN_PREPARED = 270;
  static const int NO_FREEZE_IS_SCHEDULED = 271;
  static const int UPDATE_FILE_HASH_CHANGED_SINCE_PREPARE_UPGRADE = 272;
  static const int FREEZE_START_TIME_MUST_BE_FUTURE = 273;
  static const int PREPARED_UPDATE_FILE_IS_IMMUTABLE = 274;
  static const int FREEZE_ALREADY_SCHEDULED = 275;
  static const int FREEZE_UPGRADE_IN_PROGRESS = 276;
  static const int UPDATE_FILE_ID_DOES_NOT_MATCH_PREPARED = 277;
  static const int UPDATE_FILE_HASH_DOES_NOT_MATCH_PREPARED = 278;
  static const int CONSENSUS_GAS_EXHAUSTED = 279;
  static const int REVERTED_SUCCESS = 280;
  static const int MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED = 281;
  static const int INVALID_ALIAS_KEY = 282;
  static const int UNEXPECTED_TOKEN_DECIMALS = 283;
  static const int INVALID_PROXY_ACCOUNT_ID = 284; // [Deprecated]
  static const int INVALID_TRANSFER_ACCOUNT_ID = 285;
  static const int INVALID_FEE_COLLECTOR_ACCOUNT_ID = 286;
  static const int ALIAS_IS_IMMUTABLE = 287;
  static const int SPENDER_ACCOUNT_SAME_AS_OWNER = 288;
  static const int AMOUNT_EXCEEDS_TOKEN_MAX_SUPPLY = 289;
  static const int NEGATIVE_ALLOWANCE_AMOUNT = 290;
  static const int CANNOT_APPROVE_FOR_ALL_FUNGIBLE_COMMON = 291; // [Deprecated]
  static const int SPENDER_DOES_NOT_HAVE_ALLOWANCE = 292;
  static const int AMOUNT_EXCEEDS_ALLOWANCE = 293;
  static const int MAX_ALLOWANCES_EXCEEDED = 294;
  static const int EMPTY_ALLOWANCES = 295;
  static const int SPENDER_ACCOUNT_REPEATED_IN_ALLOWANCES = 296; // [Deprecated]
  static const int REPEATED_SERIAL_NUMS_IN_NFT_ALLOWANCES = 297; // [Deprecated]
  static const int FUNGIBLE_TOKEN_IN_NFT_ALLOWANCES = 298;
  static const int NFT_IN_FUNGIBLE_TOKEN_ALLOWANCES = 299;
  static const int INVALID_ALLOWANCE_OWNER_ID = 300;
  static const int INVALID_ALLOWANCE_SPENDER_ID = 301;
  static const int REPEATED_ALLOWANCES_TO_DELETE = 302; // [Deprecated]
  static const int INVALID_DELEGATING_SPENDER = 303;
  static const int DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL = 304;
  static const int DELEGATING_SPENDER_DOES_NOT_HAVE_APPROVE_FOR_ALL = 305;
  static const int SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE = 306;
  static const int SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME =
      307;
  static const int SCHEDULE_FUTURE_THROTTLE_EXCEEDED = 308;
  static const int SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED = 309;
  static const int INVALID_ETHEREUM_TRANSACTION = 310;
  static const int WRONG_CHAIN_ID = 311;
  static const int WRONG_NONCE = 312;
  static const int ACCESS_LIST_UNSUPPORTED = 313;
  static const int SCHEDULE_PENDING_EXPIRATION = 314;
  static const int CONTRACT_IS_TOKEN_TREASURY = 315;
  static const int CONTRACT_HAS_NON_ZERO_TOKEN_BALANCES = 316;
  static const int CONTRACT_EXPIRED_AND_PENDING_REMOVAL = 317;
  static const int CONTRACT_HAS_NO_AUTO_RENEW_ACCOUNT = 318;
  static const int PERMANENT_REMOVAL_REQUIRES_SYSTEM_INITIATION = 319;
  static const int PROXY_ACCOUNT_ID_FIELD_IS_DEPRECATED = 320;
  static const int SELF_STAKING_IS_NOT_ALLOWED = 321;
  static const int INVALID_STAKING_ID = 322;
  static const int STAKING_NOT_ENABLED = 323;
  static const int INVALID_PRNG_RANGE = 324;
  static const int MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED = 325;
  static const int INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE = 326;
  static const int INSUFFICIENT_BALANCES_FOR_STORAGE_RENT = 327;
  static const int MAX_CHILD_RECORDS_EXCEEDED = 328;
  static const int INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES = 329;
  static const int TRANSACTION_HAS_UNKNOWN_FIELDS = 330;
  static const int ACCOUNT_IS_IMMUTABLE = 331;
  static const int ALIAS_ALREADY_ASSIGNED = 332;
  static const int INVALID_METADATA_KEY = 333;
  static const int TOKEN_HAS_NO_METADATA_KEY = 334;
  static const int MISSING_TOKEN_METADATA = 335;
  static const int MISSING_SERIAL_NUMBERS = 336;
  static const int TOKEN_HAS_NO_ADMIN_KEY = 337;
  static const int NODE_DELETED = 338;
  static const int INVALID_NODE_ID = 339;
  static const int INVALID_GOSSIP_ENDPOINT = 340;
  static const int INVALID_NODE_ACCOUNT_ID = 341;
  static const int INVALID_NODE_DESCRIPTION = 342;
  static const int INVALID_SERVICE_ENDPOINT = 343;
  static const int INVALID_GOSSIP_CAE_CERTIFICATE = 344;
  static const int INVALID_GRPC_CERTIFICATE = 345;
  static const int INVALID_MAX_AUTO_ASSOCIATIONS = 346;
  static const int MAX_NODES_CREATED = 347;
  static const int IP_FQDN_CANNOT_BE_SET_FOR_SAME_ENDPOINT = 348;
  static const int GOSSIP_ENDPOINT_CANNOT_HAVE_FQDN = 349;
  static const int FQDN_SIZE_TOO_LARGE = 350;
  static const int INVALID_ENDPOINT = 351;
  static const int GOSSIP_ENDPOINTS_EXCEEDED_LIMIT = 352;
  static const int TOKEN_REFERENCE_REPEATED = 353;
  static const int INVALID_OWNER_ID = 354;
  static const int TOKEN_REFERENCE_LIST_SIZE_LIMIT_EXCEEDED = 355;
  static const int INVALID_IPV4_ADDRESS = 356;
  static const int SERVICE_ENDPOINTS_EXCEEDED_LIMIT = 357;
  static const int EMPTY_TOKEN_REFERENCE_LIST = 358;
  static const int UPDATE_NODE_ACCOUNT_NOT_ALLOWED = 359;
  static const int TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY = 360;
  static const int EMPTY_PENDING_AIRDROP_ID_LIST = 361;
  static const int PENDING_AIRDROP_ID_REPEATED = 362;
  static const int MAX_PENDING_AIRDROP_ID_EXCEEDED = 363;
  static const int PENDING_NFT_AIRDROP_ALREADY_EXISTS = 364;
  static const int ACCOUNT_HAS_PENDING_AIRDROPS = 365;
  static const int THROTTLED_AT_CONSENSUS = 366;
  static const int INVALID_PENDING_AIRDROP_ID = 367;
  static const int TOKEN_AIRDROP_WITH_FALLBACK_ROYALTY = 368;
  static const int INVALID_TOKEN_ID_PENDING_AIRDROP = 369;
  static const int SCHEDULE_EXPIRY_IS_BUSY = 370;
  static const int INVALID_GRPC_CERTIFICATE_HASH = 371;
  static const int MISSING_EXPIRY_TIME = 372;
  static const int NO_SCHEDULING_ALLOWED_AFTER_SCHEDULED_RECURSION = 373;
  static const int RECURSIVE_SCHEDULING_LIMIT_REACHED = 374;
  static const int WAITING_FOR_LEDGER_ID = 375;
  static const int MAX_ENTRIES_FOR_FEE_EXEMPT_KEY_LIST_EXCEEDED = 376;
  static const int FEE_EXEMPT_KEY_LIST_CONTAINS_DUPLICATED_KEYS = 377;
  static const int INVALID_KEY_IN_FEE_EXEMPT_KEY_LIST = 378;
  static const int INVALID_FEE_SCHEDULE_KEY = 379;
  static const int FEE_SCHEDULE_KEY_CANNOT_BE_UPDATED = 380;
  static const int FEE_SCHEDULE_KEY_NOT_SET = 381;
  static const int MAX_CUSTOM_FEE_LIMIT_EXCEEDED = 382;
  static const int NO_VALID_MAX_CUSTOM_FEE = 383;
  static const int INVALID_MAX_CUSTOM_FEES = 384;
  static const int DUPLICATE_DENOMINATION_IN_MAX_CUSTOM_FEE_LIST = 385;
  static const int DUPLICATE_ACCOUNT_ID_IN_MAX_CUSTOM_FEE_LIST = 386;
  static const int MAX_CUSTOM_FEES_IS_NOT_SUPPORTED = 387;
  static const int BATCH_LIST_EMPTY = 388;
  static const int BATCH_LIST_CONTAINS_DUPLICATES = 389;
  static const int BATCH_TRANSACTION_IN_BLACKLIST = 390;
  static const int INNER_TRANSACTION_FAILED = 391;
  static const int MISSING_BATCH_KEY = 392;
  static const int BATCH_KEY_SET_ON_NON_INNER_TRANSACTION = 393;
  static const int INVALID_BATCH_KEY = 394;

  factory ResponseCode(int code) {
    final name = _knownNames[code] ?? 'UNKNOWN_CODE_$code';
    return ResponseCode._(code, name);
  }

  bool get isUnknown => name.startsWith('UNKNOWN_CODE_');

  @Deprecated(
    'The getName method will be deprecated in v0.1.4. '
    'Use ResponseCode(code).name instead.',
  )
  static String getName(int code) => ResponseCode(code).name;

  static const Map<int, String> _knownNames = <int, String>{
    OK: 'OK',
    INVALID_TRANSACTION: 'INVALID_TRANSACTION',
    PAYER_ACCOUNT_NOT_FOUND: 'PAYER_ACCOUNT_NOT_FOUND',
    INVALID_NODE_ACCOUNT: 'INVALID_NODE_ACCOUNT',
    TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',
    INVALID_TRANSACTION_START: 'INVALID_TRANSACTION_START',
    INVALID_TRANSACTION_DURATION: 'INVALID_TRANSACTION_DURATION',
    INVALID_SIGNATURE: 'INVALID_SIGNATURE',
    MEMO_TOO_LONG: 'MEMO_TOO_LONG',
    INSUFFICIENT_TX_FEE: 'INSUFFICIENT_TX_FEE',
    INSUFFICIENT_PAYER_BALANCE: 'INSUFFICIENT_PAYER_BALANCE',
    DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
    BUSY: 'BUSY',
    NOT_SUPPORTED: 'NOT_SUPPORTED',
    INVALID_FILE_ID: 'INVALID_FILE_ID',
    INVALID_ACCOUNT_ID: 'INVALID_ACCOUNT_ID',
    INVALID_CONTRACT_ID: 'INVALID_CONTRACT_ID',
    INVALID_TRANSACTION_ID: 'INVALID_TRANSACTION_ID',
    RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    INVALID_SOLIDITY_ID: 'INVALID_SOLIDITY_ID',
    UNKNOWN: 'UNKNOWN',
    SUCCESS: 'SUCCESS',
    FAIL_INVALID: 'FAIL_INVALID',
    FAIL_FEE: 'FAIL_FEE',
    FAIL_BALANCE: 'FAIL_BALANCE',
    KEY_REQUIRED: 'KEY_REQUIRED',
    BAD_ENCODING: 'BAD_ENCODING',
    INSUFFICIENT_ACCOUNT_BALANCE: 'INSUFFICIENT_ACCOUNT_BALANCE',
    INVALID_SOLIDITY_ADDRESS: 'INVALID_SOLIDITY_ADDRESS',
    INSUFFICIENT_GAS: 'INSUFFICIENT_GAS',
    CONTRACT_SIZE_LIMIT_EXCEEDED: 'CONTRACT_SIZE_LIMIT_EXCEEDED',
    LOCAL_CALL_MODIFICATION_EXCEPTION: 'LOCAL_CALL_MODIFICATION_EXCEPTION',
    CONTRACT_REVERT_EXECUTED: 'CONTRACT_REVERT_EXECUTED',
    CONTRACT_EXECUTION_EXCEPTION: 'CONTRACT_EXECUTION_EXCEPTION',
    INVALID_RECEIVING_NODE_ACCOUNT: 'INVALID_RECEIVING_NODE_ACCOUNT',
    MISSING_QUERY_HEADER: 'MISSING_QUERY_HEADER',
    ACCOUNT_UPDATE_FAILED: 'ACCOUNT_UPDATE_FAILED',
    INVALID_KEY_ENCODING: 'INVALID_KEY_ENCODING',
    NULL_SOLIDITY_ADDRESS: 'NULL_SOLIDITY_ADDRESS',
    CONTRACT_UPDATE_FAILED: 'CONTRACT_UPDATE_FAILED',
    INVALID_QUERY_HEADER: 'INVALID_QUERY_HEADER',
    INVALID_FEE_SUBMITTED: 'INVALID_FEE_SUBMITTED',
    INVALID_PAYER_SIGNATURE: 'INVALID_PAYER_SIGNATURE',
    KEY_NOT_PROVIDED: 'KEY_NOT_PROVIDED',
    INVALID_EXPIRATION_TIME: 'INVALID_EXPIRATION_TIME',
    NO_WACL_KEY: 'NO_WACL_KEY',
    FILE_CONTENT_EMPTY: 'FILE_CONTENT_EMPTY',
    INVALID_ACCOUNT_AMOUNTS: 'INVALID_ACCOUNT_AMOUNTS',
    EMPTY_TRANSACTION_BODY: 'EMPTY_TRANSACTION_BODY',
    INVALID_TRANSACTION_BODY: 'INVALID_TRANSACTION_BODY',
    INVALID_SIGNATURE_TYPE_MISMATCHING_KEY:
        'INVALID_SIGNATURE_TYPE_MISMATCHING_KEY',
    INVALID_SIGNATURE_COUNT_MISMATCHING_KEY:
        'INVALID_SIGNATURE_COUNT_MISMATCHING_KEY',
    EMPTY_LIVE_HASH_BODY: 'EMPTY_LIVE_HASH_BODY',
    EMPTY_LIVE_HASH: 'EMPTY_LIVE_HASH',
    EMPTY_LIVE_HASH_KEYS: 'EMPTY_LIVE_HASH_KEYS',
    INVALID_LIVE_HASH_SIZE: 'INVALID_LIVE_HASH_SIZE',
    EMPTY_QUERY_BODY: 'EMPTY_QUERY_BODY',
    EMPTY_LIVE_HASH_QUERY: 'EMPTY_LIVE_HASH_QUERY',
    LIVE_HASH_NOT_FOUND: 'LIVE_HASH_NOT_FOUND',
    ACCOUNT_ID_DOES_NOT_EXIST: 'ACCOUNT_ID_DOES_NOT_EXIST',
    LIVE_HASH_ALREADY_EXISTS: 'LIVE_HASH_ALREADY_EXISTS',
    INVALID_FILE_WACL: 'INVALID_FILE_WACL',
    SERIALIZATION_FAILED: 'SERIALIZATION_FAILED',
    TRANSACTION_OVERSIZE: 'TRANSACTION_OVERSIZE',
    TRANSACTION_TOO_MANY_LAYERS: 'TRANSACTION_TOO_MANY_LAYERS',
    CONTRACT_DELETED: 'CONTRACT_DELETED',
    PLATFORM_NOT_ACTIVE: 'PLATFORM_NOT_ACTIVE',
    KEY_PREFIX_MISMATCH: 'KEY_PREFIX_MISMATCH',
    PLATFORM_TRANSACTION_NOT_CREATED: 'PLATFORM_TRANSACTION_NOT_CREATED',
    INVALID_RENEWAL_PERIOD: 'INVALID_RENEWAL_PERIOD',
    INVALID_PAYER_ACCOUNT_ID: 'INVALID_PAYER_ACCOUNT_ID',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    FILE_DELETED: 'FILE_DELETED',
    ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS: 'ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS',
    SETTING_NEGATIVE_ACCOUNT_BALANCE: 'SETTING_NEGATIVE_ACCOUNT_BALANCE',
    OBTAINER_REQUIRED: 'OBTAINER_REQUIRED',
    OBTAINER_SAME_CONTRACT_ID: 'OBTAINER_SAME_CONTRACT_ID',
    OBTAINER_DOES_NOT_EXIST: 'OBTAINER_DOES_NOT_EXIST',
    MODIFYING_IMMUTABLE_CONTRACT: 'MODIFYING_IMMUTABLE_CONTRACT',
    FILE_SYSTEM_EXCEPTION: 'FILE_SYSTEM_EXCEPTION',
    AUTORENEW_DURATION_NOT_IN_RANGE: 'AUTORENEW_DURATION_NOT_IN_RANGE',
    ERROR_DECODING_BYTESTRING: 'ERROR_DECODING_BYTESTRING',
    CONTRACT_FILE_EMPTY: 'CONTRACT_FILE_EMPTY',
    CONTRACT_BYTECODE_EMPTY: 'CONTRACT_BYTECODE_EMPTY',
    INVALID_INITIAL_BALANCE: 'INVALID_INITIAL_BALANCE',
    INVALID_RECEIVE_RECORD_THRESHOLD: 'INVALID_RECEIVE_RECORD_THRESHOLD',
    INVALID_SEND_RECORD_THRESHOLD: 'INVALID_SEND_RECORD_THRESHOLD',
    ACCOUNT_IS_NOT_GENESIS_ACCOUNT: 'ACCOUNT_IS_NOT_GENESIS_ACCOUNT',
    PAYER_ACCOUNT_UNAUTHORIZED: 'PAYER_ACCOUNT_UNAUTHORIZED',
    INVALID_FREEZE_TRANSACTION_BODY: 'INVALID_FREEZE_TRANSACTION_BODY',
    FREEZE_TRANSACTION_BODY_NOT_FOUND: 'FREEZE_TRANSACTION_BODY_NOT_FOUND',
    TRANSFER_LIST_SIZE_LIMIT_EXCEEDED: 'TRANSFER_LIST_SIZE_LIMIT_EXCEEDED',
    RESULT_SIZE_LIMIT_EXCEEDED: 'RESULT_SIZE_LIMIT_EXCEEDED',
    NOT_SPECIAL_ACCOUNT: 'NOT_SPECIAL_ACCOUNT',
    CONTRACT_NEGATIVE_GAS: 'CONTRACT_NEGATIVE_GAS',
    CONTRACT_NEGATIVE_VALUE: 'CONTRACT_NEGATIVE_VALUE',
    INVALID_FEE_FILE: 'INVALID_FEE_FILE',
    INVALID_EXCHANGE_RATE_FILE: 'INVALID_EXCHANGE_RATE_FILE',
    INSUFFICIENT_LOCAL_CALL_GAS: 'INSUFFICIENT_LOCAL_CALL_GAS',
    ENTITY_NOT_ALLOWED_TO_DELETE: 'ENTITY_NOT_ALLOWED_TO_DELETE',
    AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
    FILE_UPLOADED_PROTO_INVALID: 'FILE_UPLOADED_PROTO_INVALID',
    FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK:
        'FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK',
    FEE_SCHEDULE_FILE_PART_UPLOADED: 'FEE_SCHEDULE_FILE_PART_UPLOADED',
    EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED: 'EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED',
    MAX_CONTRACT_STORAGE_EXCEEDED: 'MAX_CONTRACT_STORAGE_EXCEEDED',
    TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT:
        'TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT',
    TOTAL_LEDGER_BALANCE_INVALID: 'TOTAL_LEDGER_BALANCE_INVALID',
    EXPIRATION_REDUCTION_NOT_ALLOWED: 'EXPIRATION_REDUCTION_NOT_ALLOWED',
    MAX_GAS_LIMIT_EXCEEDED: 'MAX_GAS_LIMIT_EXCEEDED',
    MAX_FILE_SIZE_EXCEEDED: 'MAX_FILE_SIZE_EXCEEDED',
    INVALID_TOPIC_ID: 'INVALID_TOPIC_ID',
    INVALID_ADMIN_KEY: 'INVALID_ADMIN_KEY',
    INVALID_SUBMIT_KEY: 'INVALID_SUBMIT_KEY',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOPIC_MESSAGE: 'INVALID_TOPIC_MESSAGE',
    INVALID_AUTORENEW_ACCOUNT: 'INVALID_AUTORENEW_ACCOUNT',
    AUTORENEW_ACCOUNT_NOT_ALLOWED: 'AUTORENEW_ACCOUNT_NOT_ALLOWED',
    TOPIC_EXPIRED: 'TOPIC_EXPIRED',
    INVALID_CHUNK_NUMBER: 'INVALID_CHUNK_NUMBER',
    INVALID_CHUNK_TRANSACTION_ID: 'INVALID_CHUNK_TRANSACTION_ID',
    ACCOUNT_FROZEN_FOR_TOKEN: 'ACCOUNT_FROZEN_FOR_TOKEN',
    TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED: 'TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED',
    INVALID_TOKEN_ID: 'INVALID_TOKEN_ID',
    INVALID_TOKEN_DECIMALS: 'INVALID_TOKEN_DECIMALS',
    INVALID_TOKEN_INITIAL_SUPPLY: 'INVALID_TOKEN_INITIAL_SUPPLY',
    INVALID_TREASURY_ACCOUNT_FOR_TOKEN: 'INVALID_TREASURY_ACCOUNT_FOR_TOKEN',
    INVALID_TOKEN_SYMBOL: 'INVALID_TOKEN_SYMBOL',
    TOKEN_HAS_NO_FREEZE_KEY: 'TOKEN_HAS_NO_FREEZE_KEY',
    TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN: 'TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN',
    MISSING_TOKEN_SYMBOL: 'MISSING_TOKEN_SYMBOL',
    TOKEN_SYMBOL_TOO_LONG: 'TOKEN_SYMBOL_TOO_LONG',
    ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN: 'ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN',
    TOKEN_HAS_NO_KYC_KEY: 'TOKEN_HAS_NO_KYC_KEY',
    INSUFFICIENT_TOKEN_BALANCE: 'INSUFFICIENT_TOKEN_BALANCE',
    TOKEN_WAS_DELETED: 'TOKEN_WAS_DELETED',
    TOKEN_HAS_NO_SUPPLY_KEY: 'TOKEN_HAS_NO_SUPPLY_KEY',
    TOKEN_HAS_NO_WIPE_KEY: 'TOKEN_HAS_NO_WIPE_KEY',
    INVALID_TOKEN_MINT_AMOUNT: 'INVALID_TOKEN_MINT_AMOUNT',
    INVALID_TOKEN_BURN_AMOUNT: 'INVALID_TOKEN_BURN_AMOUNT',
    TOKEN_NOT_ASSOCIATED_TO_ACCOUNT: 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT',
    CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT: 'CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT',
    INVALID_KYC_KEY: 'INVALID_KYC_KEY',
    INVALID_WIPE_KEY: 'INVALID_WIPE_KEY',
    INVALID_FREEZE_KEY: 'INVALID_FREEZE_KEY',
    INVALID_SUPPLY_KEY: 'INVALID_SUPPLY_KEY',
    MISSING_TOKEN_NAME: 'MISSING_TOKEN_NAME',
    TOKEN_NAME_TOO_LONG: 'TOKEN_NAME_TOO_LONG',
    INVALID_WIPING_AMOUNT: 'INVALID_WIPING_AMOUNT',
    TOKEN_IS_IMMUTABLE: 'TOKEN_IS_IMMUTABLE',
    TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT: 'TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT',
    TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES:
        'TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES',
    ACCOUNT_IS_TREASURY: 'ACCOUNT_IS_TREASURY',
    TOKEN_ID_REPEATED_IN_TOKEN_LIST: 'TOKEN_ID_REPEATED_IN_TOKEN_LIST',
    TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED:
        'TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED',
    EMPTY_TOKEN_TRANSFER_BODY: 'EMPTY_TOKEN_TRANSFER_BODY',
    EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS:
        'EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS',
    INVALID_SCHEDULE_ID: 'INVALID_SCHEDULE_ID',
    SCHEDULE_IS_IMMUTABLE: 'SCHEDULE_IS_IMMUTABLE',
    INVALID_SCHEDULE_PAYER_ID: 'INVALID_SCHEDULE_PAYER_ID',
    INVALID_SCHEDULE_ACCOUNT_ID: 'INVALID_SCHEDULE_ACCOUNT_ID',
    NO_NEW_VALID_SIGNATURES: 'NO_NEW_VALID_SIGNATURES',
    UNRESOLVABLE_REQUIRED_SIGNERS: 'UNRESOLVABLE_REQUIRED_SIGNERS',
    SCHEDULED_TRANSACTION_NOT_IN_WHITELIST:
        'SCHEDULED_TRANSACTION_NOT_IN_WHITELIST',
    SOME_SIGNATURES_WERE_INVALID: 'SOME_SIGNATURES_WERE_INVALID',
    TRANSACTION_ID_FIELD_NOT_ALLOWED: 'TRANSACTION_ID_FIELD_NOT_ALLOWED',
    IDENTICAL_SCHEDULE_ALREADY_CREATED: 'IDENTICAL_SCHEDULE_ALREADY_CREATED',
    INVALID_ZERO_BYTE_IN_STRING: 'INVALID_ZERO_BYTE_IN_STRING',
    SCHEDULE_ALREADY_DELETED: 'SCHEDULE_ALREADY_DELETED',
    SCHEDULE_ALREADY_EXECUTED: 'SCHEDULE_ALREADY_EXECUTED',
    MESSAGE_SIZE_TOO_LARGE: 'MESSAGE_SIZE_TOO_LARGE',
    OPERATION_REPEATED_IN_BUCKET_GROUPS: 'OPERATION_REPEATED_IN_BUCKET_GROUPS',
    BUCKET_CAPACITY_OVERFLOW: 'BUCKET_CAPACITY_OVERFLOW',
    NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION:
        'NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION',
    BUCKET_HAS_NO_THROTTLE_GROUPS: 'BUCKET_HAS_NO_THROTTLE_GROUPS',
    THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC: 'THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC',
    SUCCESS_BUT_MISSING_EXPECTED_OPERATION:
        'SUCCESS_BUT_MISSING_EXPECTED_OPERATION',
    UNPARSEABLE_THROTTLE_DEFINITIONS: 'UNPARSEABLE_THROTTLE_DEFINITIONS',
    INVALID_THROTTLE_DEFINITIONS: 'INVALID_THROTTLE_DEFINITIONS',
    ACCOUNT_EXPIRED_AND_PENDING_REMOVAL: 'ACCOUNT_EXPIRED_AND_PENDING_REMOVAL',
    INVALID_TOKEN_MAX_SUPPLY: 'INVALID_TOKEN_MAX_SUPPLY',
    INVALID_TOKEN_NFT_SERIAL_NUMBER: 'INVALID_TOKEN_NFT_SERIAL_NUMBER',
    INVALID_NFT_ID: 'INVALID_NFT_ID',
    METADATA_TOO_LONG: 'METADATA_TOO_LONG',
    BATCH_SIZE_LIMIT_EXCEEDED: 'BATCH_SIZE_LIMIT_EXCEEDED',
    INVALID_QUERY_RANGE: 'INVALID_QUERY_RANGE',
    FRACTION_DIVIDES_BY_ZERO: 'FRACTION_DIVIDES_BY_ZERO',
    INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE:
        'INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE',
    CUSTOM_FEES_LIST_TOO_LONG: 'CUSTOM_FEES_LIST_TOO_LONG',
    INVALID_CUSTOM_FEE_COLLECTOR: 'INVALID_CUSTOM_FEE_COLLECTOR',
    INVALID_TOKEN_ID_IN_CUSTOM_FEES: 'INVALID_TOKEN_ID_IN_CUSTOM_FEES',
    TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR:
        'TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR',
    TOKEN_MAX_SUPPLY_REACHED: 'TOKEN_MAX_SUPPLY_REACHED',
    SENDER_DOES_NOT_OWN_NFT_SERIAL_NO: 'SENDER_DOES_NOT_OWN_NFT_SERIAL_NO',
    CUSTOM_FEE_NOT_FULLY_SPECIFIED: 'CUSTOM_FEE_NOT_FULLY_SPECIFIED',
    CUSTOM_FEE_MUST_BE_POSITIVE: 'CUSTOM_FEE_MUST_BE_POSITIVE',
    TOKEN_HAS_NO_FEE_SCHEDULE_KEY: 'TOKEN_HAS_NO_FEE_SCHEDULE_KEY',
    CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE: 'CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE',
    ROYALTY_FRACTION_CANNOT_EXCEED_ONE: 'ROYALTY_FRACTION_CANNOT_EXCEED_ONE',
    FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT:
        'FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT',
    CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES: 'CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES',
    CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON:
        'CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON',
    CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON:
        'CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON',
    INVALID_CUSTOM_FEE_SCHEDULE_KEY: 'INVALID_CUSTOM_FEE_SCHEDULE_KEY',
    INVALID_TOKEN_MINT_METADATA: 'INVALID_TOKEN_MINT_METADATA',
    INVALID_TOKEN_BURN_METADATA: 'INVALID_TOKEN_BURN_METADATA',
    CURRENT_TREASURY_STILL_OWNS_NFTS: 'CURRENT_TREASURY_STILL_OWNS_NFTS',
    ACCOUNT_STILL_OWNS_NFTS: 'ACCOUNT_STILL_OWNS_NFTS',
    TREASURY_MUST_OWN_BURNED_NFT: 'TREASURY_MUST_OWN_BURNED_NFT',
    ACCOUNT_DOES_NOT_OWN_WIPED_NFT: 'ACCOUNT_DOES_NOT_OWN_WIPED_NFT',
    ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON:
        'ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON',
    MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED:
        'MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED',
    PAYER_ACCOUNT_DELETED: 'PAYER_ACCOUNT_DELETED',
    CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH:
        'CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH',
    CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS:
        'CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS',
    INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE:
        'INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE',
    SERIAL_NUMBER_LIMIT_REACHED: 'SERIAL_NUMBER_LIMIT_REACHED',
    CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE:
        'CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE',
    NO_REMAINING_AUTOMATIC_ASSOCIATIONS: 'NO_REMAINING_AUTOMATIC_ASSOCIATIONS',
    EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT:
        'EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT',
    REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT:
        'REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT',
    TOKEN_IS_PAUSED: 'TOKEN_IS_PAUSED',
    TOKEN_HAS_NO_PAUSE_KEY: 'TOKEN_HAS_NO_PAUSE_KEY',
    INVALID_PAUSE_KEY: 'INVALID_PAUSE_KEY',
    FREEZE_UPDATE_FILE_DOES_NOT_EXIST: 'FREEZE_UPDATE_FILE_DOES_NOT_EXIST',
    FREEZE_UPDATE_FILE_HASH_DOES_NOT_MATCH:
        'FREEZE_UPDATE_FILE_HASH_DOES_NOT_MATCH',
    NO_UPGRADE_HAS_BEEN_PREPARED: 'NO_UPGRADE_HAS_BEEN_PREPARED',
    NO_FREEZE_IS_SCHEDULED: 'NO_FREEZE_IS_SCHEDULED',
    UPDATE_FILE_HASH_CHANGED_SINCE_PREPARE_UPGRADE:
        'UPDATE_FILE_HASH_CHANGED_SINCE_PREPARE_UPGRADE',
    FREEZE_START_TIME_MUST_BE_FUTURE: 'FREEZE_START_TIME_MUST_BE_FUTURE',
    PREPARED_UPDATE_FILE_IS_IMMUTABLE: 'PREPARED_UPDATE_FILE_IS_IMMUTABLE',
    FREEZE_ALREADY_SCHEDULED: 'FREEZE_ALREADY_SCHEDULED',
    FREEZE_UPGRADE_IN_PROGRESS: 'FREEZE_UPGRADE_IN_PROGRESS',
    UPDATE_FILE_ID_DOES_NOT_MATCH_PREPARED:
        'UPDATE_FILE_ID_DOES_NOT_MATCH_PREPARED',
    UPDATE_FILE_HASH_DOES_NOT_MATCH_PREPARED:
        'UPDATE_FILE_HASH_DOES_NOT_MATCH_PREPARED',
    CONSENSUS_GAS_EXHAUSTED: 'CONSENSUS_GAS_EXHAUSTED',
    REVERTED_SUCCESS: 'REVERTED_SUCCESS',
    MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED:
        'MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED',
    INVALID_ALIAS_KEY: 'INVALID_ALIAS_KEY',
    UNEXPECTED_TOKEN_DECIMALS: 'UNEXPECTED_TOKEN_DECIMALS',
    INVALID_PROXY_ACCOUNT_ID: 'INVALID_PROXY_ACCOUNT_ID',
    INVALID_TRANSFER_ACCOUNT_ID: 'INVALID_TRANSFER_ACCOUNT_ID',
    INVALID_FEE_COLLECTOR_ACCOUNT_ID: 'INVALID_FEE_COLLECTOR_ACCOUNT_ID',
    ALIAS_IS_IMMUTABLE: 'ALIAS_IS_IMMUTABLE',
    SPENDER_ACCOUNT_SAME_AS_OWNER: 'SPENDER_ACCOUNT_SAME_AS_OWNER',
    AMOUNT_EXCEEDS_TOKEN_MAX_SUPPLY: 'AMOUNT_EXCEEDS_TOKEN_MAX_SUPPLY',
    NEGATIVE_ALLOWANCE_AMOUNT: 'NEGATIVE_ALLOWANCE_AMOUNT',
    CANNOT_APPROVE_FOR_ALL_FUNGIBLE_COMMON:
        'CANNOT_APPROVE_FOR_ALL_FUNGIBLE_COMMON',
    SPENDER_DOES_NOT_HAVE_ALLOWANCE: 'SPENDER_DOES_NOT_HAVE_ALLOWANCE',
    AMOUNT_EXCEEDS_ALLOWANCE: 'AMOUNT_EXCEEDS_ALLOWANCE',
    MAX_ALLOWANCES_EXCEEDED: 'MAX_ALLOWANCES_EXCEEDED',
    EMPTY_ALLOWANCES: 'EMPTY_ALLOWANCES',
    SPENDER_ACCOUNT_REPEATED_IN_ALLOWANCES:
        'SPENDER_ACCOUNT_REPEATED_IN_ALLOWANCES',
    REPEATED_SERIAL_NUMS_IN_NFT_ALLOWANCES:
        'REPEATED_SERIAL_NUMS_IN_NFT_ALLOWANCES',
    FUNGIBLE_TOKEN_IN_NFT_ALLOWANCES: 'FUNGIBLE_TOKEN_IN_NFT_ALLOWANCES',
    NFT_IN_FUNGIBLE_TOKEN_ALLOWANCES: 'NFT_IN_FUNGIBLE_TOKEN_ALLOWANCES',
    INVALID_ALLOWANCE_OWNER_ID: 'INVALID_ALLOWANCE_OWNER_ID',
    INVALID_ALLOWANCE_SPENDER_ID: 'INVALID_ALLOWANCE_SPENDER_ID',
    REPEATED_ALLOWANCES_TO_DELETE: 'REPEATED_ALLOWANCES_TO_DELETE',
    INVALID_DELEGATING_SPENDER: 'INVALID_DELEGATING_SPENDER',
    DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL:
        'DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL',
    DELEGATING_SPENDER_DOES_NOT_HAVE_APPROVE_FOR_ALL:
        'DELEGATING_SPENDER_DOES_NOT_HAVE_APPROVE_FOR_ALL',
    SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE:
        'SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE',
    SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME:
        'SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME',
    SCHEDULE_FUTURE_THROTTLE_EXCEEDED: 'SCHEDULE_FUTURE_THROTTLE_EXCEEDED',
    SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED: 'SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED',
    INVALID_ETHEREUM_TRANSACTION: 'INVALID_ETHEREUM_TRANSACTION',
    WRONG_CHAIN_ID: 'WRONG_CHAIN_ID',
    WRONG_NONCE: 'WRONG_NONCE',
    ACCESS_LIST_UNSUPPORTED: 'ACCESS_LIST_UNSUPPORTED',
    SCHEDULE_PENDING_EXPIRATION: 'SCHEDULE_PENDING_EXPIRATION',
    CONTRACT_IS_TOKEN_TREASURY: 'CONTRACT_IS_TOKEN_TREASURY',
    CONTRACT_HAS_NON_ZERO_TOKEN_BALANCES:
        'CONTRACT_HAS_NON_ZERO_TOKEN_BALANCES',
    CONTRACT_EXPIRED_AND_PENDING_REMOVAL:
        'CONTRACT_EXPIRED_AND_PENDING_REMOVAL',
    CONTRACT_HAS_NO_AUTO_RENEW_ACCOUNT: 'CONTRACT_HAS_NO_AUTO_RENEW_ACCOUNT',
    PERMANENT_REMOVAL_REQUIRES_SYSTEM_INITIATION:
        'PERMANENT_REMOVAL_REQUIRES_SYSTEM_INITIATION',
    PROXY_ACCOUNT_ID_FIELD_IS_DEPRECATED:
        'PROXY_ACCOUNT_ID_FIELD_IS_DEPRECATED',
    SELF_STAKING_IS_NOT_ALLOWED: 'SELF_STAKING_IS_NOT_ALLOWED',
    INVALID_STAKING_ID: 'INVALID_STAKING_ID',
    STAKING_NOT_ENABLED: 'STAKING_NOT_ENABLED',
    INVALID_PRNG_RANGE: 'INVALID_PRNG_RANGE',
    MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED:
        'MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED',
    INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE:
        'INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE',
    INSUFFICIENT_BALANCES_FOR_STORAGE_RENT:
        'INSUFFICIENT_BALANCES_FOR_STORAGE_RENT',
    MAX_CHILD_RECORDS_EXCEEDED: 'MAX_CHILD_RECORDS_EXCEEDED',
    INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES:
        'INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES',
    TRANSACTION_HAS_UNKNOWN_FIELDS: 'TRANSACTION_HAS_UNKNOWN_FIELDS',
    ACCOUNT_IS_IMMUTABLE: 'ACCOUNT_IS_IMMUTABLE',
    ALIAS_ALREADY_ASSIGNED: 'ALIAS_ALREADY_ASSIGNED',
    INVALID_METADATA_KEY: 'INVALID_METADATA_KEY',
    TOKEN_HAS_NO_METADATA_KEY: 'TOKEN_HAS_NO_METADATA_KEY',
    MISSING_TOKEN_METADATA: 'MISSING_TOKEN_METADATA',
    MISSING_SERIAL_NUMBERS: 'MISSING_SERIAL_NUMBERS',
    TOKEN_HAS_NO_ADMIN_KEY: 'TOKEN_HAS_NO_ADMIN_KEY',
    NODE_DELETED: 'NODE_DELETED',
    INVALID_NODE_ID: 'INVALID_NODE_ID',
    INVALID_GOSSIP_ENDPOINT: 'INVALID_GOSSIP_ENDPOINT',
    INVALID_NODE_ACCOUNT_ID: 'INVALID_NODE_ACCOUNT_ID',
    INVALID_NODE_DESCRIPTION: 'INVALID_NODE_DESCRIPTION',
    INVALID_SERVICE_ENDPOINT: 'INVALID_SERVICE_ENDPOINT',
    INVALID_GOSSIP_CAE_CERTIFICATE: 'INVALID_GOSSIP_CAE_CERTIFICATE',
    INVALID_GRPC_CERTIFICATE: 'INVALID_GRPC_CERTIFICATE',
    INVALID_MAX_AUTO_ASSOCIATIONS: 'INVALID_MAX_AUTO_ASSOCIATIONS',
    MAX_NODES_CREATED: 'MAX_NODES_CREATED',
    IP_FQDN_CANNOT_BE_SET_FOR_SAME_ENDPOINT:
        'IP_FQDN_CANNOT_BE_SET_FOR_SAME_ENDPOINT',
    GOSSIP_ENDPOINT_CANNOT_HAVE_FQDN: 'GOSSIP_ENDPOINT_CANNOT_HAVE_FQDN',
    FQDN_SIZE_TOO_LARGE: 'FQDN_SIZE_TOO_LARGE',
    INVALID_ENDPOINT: 'INVALID_ENDPOINT',
    GOSSIP_ENDPOINTS_EXCEEDED_LIMIT: 'GOSSIP_ENDPOINTS_EXCEEDED_LIMIT',
    TOKEN_REFERENCE_REPEATED: 'TOKEN_REFERENCE_REPEATED',
    INVALID_OWNER_ID: 'INVALID_OWNER_ID',
    TOKEN_REFERENCE_LIST_SIZE_LIMIT_EXCEEDED:
        'TOKEN_REFERENCE_LIST_SIZE_LIMIT_EXCEEDED',
    INVALID_IPV4_ADDRESS: 'INVALID_IPV4_ADDRESS',
    SERVICE_ENDPOINTS_EXCEEDED_LIMIT: 'SERVICE_ENDPOINTS_EXCEEDED_LIMIT',
    EMPTY_TOKEN_REFERENCE_LIST: 'EMPTY_TOKEN_REFERENCE_LIST',
    UPDATE_NODE_ACCOUNT_NOT_ALLOWED: 'UPDATE_NODE_ACCOUNT_NOT_ALLOWED',
    TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY: 'TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY',
    EMPTY_PENDING_AIRDROP_ID_LIST: 'EMPTY_PENDING_AIRDROP_ID_LIST',
    PENDING_AIRDROP_ID_REPEATED: 'PENDING_AIRDROP_ID_REPEATED',
    MAX_PENDING_AIRDROP_ID_EXCEEDED: 'MAX_PENDING_AIRDROP_ID_EXCEEDED',
    PENDING_NFT_AIRDROP_ALREADY_EXISTS: 'PENDING_NFT_AIRDROP_ALREADY_EXISTS',
    ACCOUNT_HAS_PENDING_AIRDROPS: 'ACCOUNT_HAS_PENDING_AIRDROPS',
    THROTTLED_AT_CONSENSUS: 'THROTTLED_AT_CONSENSUS',
    INVALID_PENDING_AIRDROP_ID: 'INVALID_PENDING_AIRDROP_ID',
    TOKEN_AIRDROP_WITH_FALLBACK_ROYALTY: 'TOKEN_AIRDROP_WITH_FALLBACK_ROYALTY',
    INVALID_TOKEN_ID_PENDING_AIRDROP: 'INVALID_TOKEN_ID_PENDING_AIRDROP',
    SCHEDULE_EXPIRY_IS_BUSY: 'SCHEDULE_EXPIRY_IS_BUSY',
    INVALID_GRPC_CERTIFICATE_HASH: 'INVALID_GRPC_CERTIFICATE_HASH',
    MISSING_EXPIRY_TIME: 'MISSING_EXPIRY_TIME',
    NO_SCHEDULING_ALLOWED_AFTER_SCHEDULED_RECURSION:
        'NO_SCHEDULING_ALLOWED_AFTER_SCHEDULED_RECURSION',
    RECURSIVE_SCHEDULING_LIMIT_REACHED: 'RECURSIVE_SCHEDULING_LIMIT_REACHED',
    WAITING_FOR_LEDGER_ID: 'WAITING_FOR_LEDGER_ID',
    MAX_ENTRIES_FOR_FEE_EXEMPT_KEY_LIST_EXCEEDED:
        'MAX_ENTRIES_FOR_FEE_EXEMPT_KEY_LIST_EXCEEDED',
    FEE_EXEMPT_KEY_LIST_CONTAINS_DUPLICATED_KEYS:
        'FEE_EXEMPT_KEY_LIST_CONTAINS_DUPLICATED_KEYS',
    INVALID_KEY_IN_FEE_EXEMPT_KEY_LIST: 'INVALID_KEY_IN_FEE_EXEMPT_KEY_LIST',
    INVALID_FEE_SCHEDULE_KEY: 'INVALID_FEE_SCHEDULE_KEY',
    FEE_SCHEDULE_KEY_CANNOT_BE_UPDATED: 'FEE_SCHEDULE_KEY_CANNOT_BE_UPDATED',
    FEE_SCHEDULE_KEY_NOT_SET: 'FEE_SCHEDULE_KEY_NOT_SET',
    MAX_CUSTOM_FEE_LIMIT_EXCEEDED: 'MAX_CUSTOM_FEE_LIMIT_EXCEEDED',
    NO_VALID_MAX_CUSTOM_FEE: 'NO_VALID_MAX_CUSTOM_FEE',
    INVALID_MAX_CUSTOM_FEES: 'INVALID_MAX_CUSTOM_FEES',
    DUPLICATE_DENOMINATION_IN_MAX_CUSTOM_FEE_LIST:
        'DUPLICATE_DENOMINATION_IN_MAX_CUSTOM_FEE_LIST',
    DUPLICATE_ACCOUNT_ID_IN_MAX_CUSTOM_FEE_LIST:
        'DUPLICATE_ACCOUNT_ID_IN_MAX_CUSTOM_FEE_LIST',
    MAX_CUSTOM_FEES_IS_NOT_SUPPORTED: 'MAX_CUSTOM_FEES_IS_NOT_SUPPORTED',
    BATCH_LIST_EMPTY: 'BATCH_LIST_EMPTY',
    BATCH_LIST_CONTAINS_DUPLICATES: 'BATCH_LIST_CONTAINS_DUPLICATES',
    BATCH_TRANSACTION_IN_BLACKLIST: 'BATCH_TRANSACTION_IN_BLACKLIST',
    INNER_TRANSACTION_FAILED: 'INNER_TRANSACTION_FAILED',
    MISSING_BATCH_KEY: 'MISSING_BATCH_KEY',
    BATCH_KEY_SET_ON_NON_INNER_TRANSACTION:
        'BATCH_KEY_SET_ON_NON_INNER_TRANSACTION',
    INVALID_BATCH_KEY: 'INVALID_BATCH_KEY',
  };
}
